"""
Sovereign Reflection Engine.
Evaluates outcomes through the critic and returns a structured fidelity verdict.
"""

import logging
from typing import Any, Dict, List, Optional

from backend.agents.critic_agent import CriticAgent

logger = logging.getLogger(__name__)


class ReflectionEngine:
    def __init__(self):
        self.critic = CriticAgent()
        logger.info("[Reflection] Critic-backed reflection engine active.")

    async def evaluate(
        self,
        response: str,
        goal: Any,
        perception: Dict[str, Any],
        results: Optional[List[Any]] = None,
    ) -> Dict[str, Any]:
        logger.info("[Reflection] Initiating Multi-Dimensional Semantic Verification...")

        objective = getattr(goal, "objective", str(goal))
        
        # 1. Structural Audit: Check execution topological consistency
        structural_audit = await self._audit_structure(results)
        
        # 2. Semantic Fidelity Check (via Critic)
        critique = await self.critic.evaluate(
            mission_id=perception.get("request_id") or "reflection",
            objective=objective,
            result={
                "response": response,
                "results": [r.dict() if hasattr(r, "dict") else r for r in (results or [])],
                "context": perception.get("context", {}),
                "structural_audit": structural_audit
            },
        )

        fidelity = float(critique.get("fidelity_score", 0.0))
        
        # 3. World Model Causal Gate (Stage 8)
        from .world_model import WorldModel
        wm = WorldModel()
        causal_audit = await wm.verify_causality(response, perception.get("intent"))
        
        # 4. Identity Bias Verification (Stage 4)
        from .identity import identity_system
        identity_audit = await identity_system.check_voice_alignment(response)

        # Aggregate Verdict
        is_valid = critique.get("is_valid", False) and causal_audit.get("is_logical", True)
        
        return {
            "score": fidelity,
            "fidelity": fidelity,
            "errors": critique.get("issues", []) + causal_audit.get("anomalies", []),
            "validated": is_valid,
            "structural_audit": structural_audit,
            "causal_audit": causal_audit,
            "identity_audit": identity_audit,
            "is_satisfactory": is_valid,
            "alignment_gap": max(0.0, 1.0 - fidelity),
        }

    async def _audit_structure(self, results: Optional[List[Any]]) -> Dict[str, Any]:
        """Verifies that the executed DAG followed topological safety rules."""
        if not results: return {"status": "skipped", "reason": "No execution results"}
        
        # Simple topological check: Ensure no results were generated by agents with failed dependencies
        anomalies = []
        for res in results:
            if hasattr(res, "failed_dependencies") and res.failed_dependencies:
                anomalies.append(f"Agent {res.agent} executed despite dependency failure.")
                
        return {
            "status": "PASS" if not anomalies else "WARN",
            "anomalies": anomalies,
            "node_count": len(results)
        }

    async def self_correct(self, response: str, evaluation: Dict[str, Any], goal: Any, perception: Dict[str, Any]) -> str:
        """Autonomous Rectification Loop."""
        if evaluation.get("is_satisfactory"):
            return response

        logger.info("[Reflection] 🚑 Self-Correction Triggered. Resolving %s issues.", len(evaluation.get("errors", [])))
        from .planner import call_lightweight_llm

        prompt = (
            f"SYSTEM: SOVEREIGN RECTIFICATION MODE\n"
            f"OBJECTIVE: {getattr(goal, 'objective', str(goal))}\n"
            f"ANOMALIES DETECTED: {evaluation.get('errors')}\n"
            f"DRAFT: {response}\n"
            "Produce a corrected, high-fidelity response that satisfies the OS safety and logic constraints."
        )
        return await call_lightweight_llm([{"role": "user", "content": prompt}])

    async def assess_mission_failure(self, mission_id: str, results: List[Any]):
        logger.warning("[Reflection] Commencing forensic audit for failed mission: %s", mission_id)
        anomalies = []
        for res in results:
            success = getattr(res, "success", True) if not isinstance(res, dict) else res.get("success", True)
            if not success:
                anomalies.append({
                    "agent": getattr(res, "agent", "unknown") if not isinstance(res, dict) else res.get("agent", "unknown"),
                    "error": str(getattr(res, "error", "Unknown anomaly")) if not isinstance(res, dict) else str(res.get("error", "Unknown anomaly")),
                })
        logger.info("[Reflection] Failure audit complete for %s. anomalies=%s", mission_id, len(anomalies))
