apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: levi-backend-dev
spec:
  template:
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: "development"
        - name: GOOGLE_CLOUD_PROJECT
          value: "levi-ai-c23c6"
        - name: FIREBASE_PROJECT_ID
          value: "levi-ai-c23c6"
        - name: WORKERS
          value: "1"
        - name: REDIS_URL
          value: ""
        resources:
          limits:
            memory: 1Gi
            cpu: "1000m"
