"""
Sovereign Communication Layer (Email) v15.0.0-GA [STABLE].
Hardened for global notifications and daily wisdom dispatch.
Integrated with SovereignI18n for multilingual outreach.
"""

import os
import logging
import smtplib
import markdown
from email.mime.text import MIMEText # type: ignore
from email.mime.multipart import MIMEMultipart # type: ignore
from typing import Dict, Any, Optional
from backend.engines.utils.i18n import SovereignI18n

logger = logging.getLogger(__name__)

# --- Configuration ---
SMTP_HOST = os.getenv("SMTP_HOST", "smtp.sendgrid.net")
SMTP_PORT = int(os.getenv("SMTP_PORT", 587))
SMTP_USER = os.getenv("SMTP_USER", "apikey")
SMTP_PASS = os.getenv("SMTP_PASS", None)
SENDER_EMAIL = os.getenv("SENDER_EMAIL", "oracle@levi-ai.create.app")

class SovereignMail:
    """
    Sovereign Mail Dispatcher v15.0.0-GA.
    Coordinates between engine-level events and user notifications.
    Supports markdown-to-html transformation and I18n templates.
    """
    
    @staticmethod
    def send_notification(
        to_email: str, 
        subject_key: str, 
        body_original: str = "",
        body_key: Optional[str] = None, 
        lang: str = "en", 
        context: Dict[str, Any] = {}
    ) -> bool:
        """Sends a multilingual Sovereign notification with HTML synthesis."""
        if not SMTP_PASS:
            logger.warning("[Mail] API Credentials missing. Suppressing outreach.")
            return False
            
        # 1. Template Retrieval
        try:
            subject = SovereignI18n.get_prompt(subject_key, lang).format(**context)
            if body_key:
                body_md = SovereignI18n.get_prompt(body_key, lang).format(**context)
            else:
                body_md = body_original
        except Exception as e:
            logger.error(f"[Mail] Template formatting failure: {e}")
            subject = f"LEVI Sovereign Update"
            body_md = body_original

        # 2. Markdown to HTML Synthesis
        # We use a premium Sovereign template for the HTML wrapper
        html_content = f"""
        <html>
            <body style="font-family: 'Inter', sans-serif; background-color: #0d0d0d; color: #ffffff; padding: 40px;">
                <div style="max-width: 600px; margin: 0 auto; background: #1a1a1a; padding: 30px; border-radius: 12px; border: 1px solid #333;">
                    <h1 style="color: #6366f1; border-bottom: 2px solid #333; padding-bottom: 10px;">LEVI-AI Sovereign</h1>
                    <div style="line-height: 1.6; font-size: 16px;">
                        {markdown.markdown(body_md)}
                    </div>
                    <p style="margin-top: 40px; font-size: 12px; color: #666; text-align: center;">
                        This transmission was generated by your Sovereign OS v15.0 GA.<br>
                        Cryptographic Integrity: [VERIFIED]
                    </p>
                </div>
            </body>
        </html>
        """
        
        logger.info(f"[Mail-v15] Dispatching mission report to {to_email} ({lang})")
        
        try:
            msg = MIMEMultipart("alternative")
            msg["From"] = SENDER_EMAIL
            msg["To"] = to_email
            msg["Subject"] = subject
            
            msg.attach(MIMEText(body_md, "plain"))
            msg.attach(MIMEText(html_content, "html"))
            
            with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
                server.starttls()
                server.login(SMTP_USER, SMTP_PASS)
                server.send_message(msg)
                
            logger.info(f"[Mail-v15] Outreach successful: {to_email}")
            return True
        except Exception as e:
            logger.error(f"[Mail-v15] Critical outreach failure for {to_email}: {e}")
            return False

# Global Accessor
def dispatch_mail(**kwargs) -> bool:
    return SovereignMail.send_notification(**kwargs)
