from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any

class IntentResult(BaseModel):
    """The result of intent classification."""
    intent: str  # chat, image, code, search, multi_step
    complexity: int = Field(1, ge=1, le=10)
    confidence: float = 1.0
    parameters: Dict[str, Any] = {}

class OrchestratorRequest(BaseModel):
    """Input to the orchestrator."""
    user_input: str
    session_id: str
    user_id: str
    user_tier: str = "free"
    mood: str = "philosophical"
    context: Optional[Dict[str, Any]] = None

class OrchestratorStep(BaseModel):
    """A single step in an execution plan."""
    step: str
    agent: str
    params: Dict[str, Any] = {}

class OrchestratorPlan(BaseModel):
    """A full plan generated by the orchestrator."""
    intent: str
    steps: List[OrchestratorStep]
    chaining_logic: str = "sequential"

class OrchestratorResponse(BaseModel):
    """Final output from the orchestrator."""
    response: str
    intent: str
    plan_executed: List[Dict[str, Any]]
    session_id: str
    job_ids: List[str] = []
