# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: backend/dcn/dcn.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'backend/dcn/dcn.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62\x61\x63kend/dcn/dcn.proto\x12\x03\x64\x63n\"P\n\x0f\x41rtifactRequest\x12\x13\n\x0b\x61rtifact_id\x18\x01 \x01(\t\x12\x12\n\nmission_id\x18\x02 \x01(\t\x12\x14\n\x0cstart_offset\x18\x03 \x01(\r\"V\n\rArtifactChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\r\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x12\x10\n\x08\x63hecksum\x18\x04 \x01(\t\"2\n\x0cPulseRequest\x12\x0f\n\x07payload\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x02 \x01(\t\"1\n\rPulseResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"M\n\tHeartbeat\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0e\n\x06region\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\x12\x0c\n\x04term\x18\x04 \x01(\r\"(\n\x10HeartbeatSummary\x12\x14\n\x0c\x61\x63tive_peers\x18\x01 \x01(\r2\xfb\x01\n\x10\x44\x43NGossipService\x12\x35\n\x0cPublishPulse\x12\x11.dcn.PulseRequest\x1a\x12.dcn.PulseResponse\x12:\n\x0fHeartbeatStream\x12\x0e.dcn.Heartbeat\x1a\x15.dcn.HeartbeatSummary(\x01\x12\x38\n\x0bPulseStream\x12\x11.dcn.PulseRequest\x1a\x12.dcn.PulseResponse(\x01\x30\x01\x12:\n\x0cPullArtifact\x12\x14.dcn.ArtifactRequest\x1a\x12.dcn.ArtifactChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backend.dcn.dcn_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARTIFACTREQUEST']._serialized_start=30
  _globals['_ARTIFACTREQUEST']._serialized_end=110
  _globals['_ARTIFACTCHUNK']._serialized_start=112
  _globals['_ARTIFACTCHUNK']._serialized_end=198
  _globals['_PULSEREQUEST']._serialized_start=200
  _globals['_PULSEREQUEST']._serialized_end=250
  _globals['_PULSERESPONSE']._serialized_start=252
  _globals['_PULSERESPONSE']._serialized_end=301
  _globals['_HEARTBEAT']._serialized_start=303
  _globals['_HEARTBEAT']._serialized_end=380
  _globals['_HEARTBEATSUMMARY']._serialized_start=382
  _globals['_HEARTBEATSUMMARY']._serialized_end=422
  _globals['_DCNGOSSIPSERVICE']._serialized_start=425
  _globals['_DCNGOSSIPSERVICE']._serialized_end=676
# @@protoc_insertion_point(module_scope)
