# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from backend.dcn import dcn_pb2 as backend_dot_dcn_dot_dcn__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in backend/dcn/dcn_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DCNGossipServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishPulse = channel.unary_unary(
                '/dcn.DCNGossipService/PublishPulse',
                request_serializer=backend_dot_dcn_dot_dcn__pb2.PulseRequest.SerializeToString,
                response_deserializer=backend_dot_dcn_dot_dcn__pb2.PulseResponse.FromString,
                _registered_method=True)
        self.HeartbeatStream = channel.stream_unary(
                '/dcn.DCNGossipService/HeartbeatStream',
                request_serializer=backend_dot_dcn_dot_dcn__pb2.Heartbeat.SerializeToString,
                response_deserializer=backend_dot_dcn_dot_dcn__pb2.HeartbeatSummary.FromString,
                _registered_method=True)
        self.PulseStream = channel.stream_stream(
                '/dcn.DCNGossipService/PulseStream',
                request_serializer=backend_dot_dcn_dot_dcn__pb2.PulseRequest.SerializeToString,
                response_deserializer=backend_dot_dcn_dot_dcn__pb2.PulseResponse.FromString,
                _registered_method=True)
        self.PullArtifact = channel.unary_stream(
                '/dcn.DCNGossipService/PullArtifact',
                request_serializer=backend_dot_dcn_dot_dcn__pb2.ArtifactRequest.SerializeToString,
                response_deserializer=backend_dot_dcn_dot_dcn__pb2.ArtifactChunk.FromString,
                _registered_method=True)


class DCNGossipServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PublishPulse(self, request, context):
        """Standard unary call for P2P gossip pulses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatStream(self, request_iterator, context):
        """Stream heartbeats for active discovery
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PulseStream(self, request_iterator, context):
        """Bidirectional stream for high-throughput pulse propagation (Phase 2.3)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullArtifact(self, request, context):
        """Phase 2.3: Chunked Artifact Transfer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DCNGossipServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishPulse': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishPulse,
                    request_deserializer=backend_dot_dcn_dot_dcn__pb2.PulseRequest.FromString,
                    response_serializer=backend_dot_dcn_dot_dcn__pb2.PulseResponse.SerializeToString,
            ),
            'HeartbeatStream': grpc.stream_unary_rpc_method_handler(
                    servicer.HeartbeatStream,
                    request_deserializer=backend_dot_dcn_dot_dcn__pb2.Heartbeat.FromString,
                    response_serializer=backend_dot_dcn_dot_dcn__pb2.HeartbeatSummary.SerializeToString,
            ),
            'PulseStream': grpc.stream_stream_rpc_method_handler(
                    servicer.PulseStream,
                    request_deserializer=backend_dot_dcn_dot_dcn__pb2.PulseRequest.FromString,
                    response_serializer=backend_dot_dcn_dot_dcn__pb2.PulseResponse.SerializeToString,
            ),
            'PullArtifact': grpc.unary_stream_rpc_method_handler(
                    servicer.PullArtifact,
                    request_deserializer=backend_dot_dcn_dot_dcn__pb2.ArtifactRequest.FromString,
                    response_serializer=backend_dot_dcn_dot_dcn__pb2.ArtifactChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dcn.DCNGossipService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dcn.DCNGossipService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DCNGossipService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PublishPulse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcn.DCNGossipService/PublishPulse',
            backend_dot_dcn_dot_dcn__pb2.PulseRequest.SerializeToString,
            backend_dot_dcn_dot_dcn__pb2.PulseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dcn.DCNGossipService/HeartbeatStream',
            backend_dot_dcn_dot_dcn__pb2.Heartbeat.SerializeToString,
            backend_dot_dcn_dot_dcn__pb2.HeartbeatSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PulseStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/dcn.DCNGossipService/PulseStream',
            backend_dot_dcn_dot_dcn__pb2.PulseRequest.SerializeToString,
            backend_dot_dcn_dot_dcn__pb2.PulseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dcn.DCNGossipService/PullArtifact',
            backend_dot_dcn_dot_dcn__pb2.ArtifactRequest.SerializeToString,
            backend_dot_dcn_dot_dcn__pb2.ArtifactChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
