# pyright: reportMissingImports=false
"""Add personas table

Revision ID: 48dff1cc8645
Revises: e08143c7b807
Create Date: 2026-03-23 22:20:40.374251

"""
from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa  # type: ignore
from sqlalchemy.dialects import sqlite  # type: ignore

# revision identifiers, used by Alembic.
revision: str = '48dff1cc8645'
down_revision: Union[str, Sequence[str], None] = 'e08143c7b807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('system_prompt', sa.String(length=2000), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_id'), 'personas', ['id'], unique=False)
    op.create_index(op.f('ix_personas_user_id'), 'personas', ['user_id'], unique=False)
    op.alter_column('analytics', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('analytics', 'chats_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('analytics', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('analytics', 'daily_users',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat_history', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.alter_column('feed_items', 'likes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('feed_items', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_feed_items_timestamp'), 'feed_items', ['timestamp'], unique=False)
    op.alter_column('model_versions', 'job_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('model_versions', 'model_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_model_versions_id'), 'model_versions', ['id'], unique=False)
    op.alter_column('payment_events', 'amount',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('payment_events', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('payment_events', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('payment_events', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('prompt_performance', 'variant_idx',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_prompt_performance_id'), 'prompt_performance', ['id'], unique=False)
    op.alter_column('push_subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quotes', 'likes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quotes', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_response_feedback_id'), 'response_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_training_data_id'), 'training_data', ['id'], unique=False)
    op.create_index(op.f('ix_training_data_session_id'), 'training_data', ['session_id'], unique=False)
    op.create_index(op.f('ix_training_data_user_id'), 'training_data', ['user_id'], unique=False)
    op.alter_column('training_jobs', 'job_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_training_jobs_id'), 'training_jobs', ['id'], unique=False)
    op.add_column('user_memory', sa.Column('structured_memory', sa.JSON(), nullable=False))
    op.alter_column('user_memory', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_memory', 'mood_history',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('user_memory', 'liked_topics',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('user_memory', 'interaction_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_memory', 'last_active',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'tier',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'credits',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'liked_topics',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('users', 'mood_history',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('users', 'share_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'bonus_credits',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bonus_credits',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'share_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'mood_history',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.alter_column('users', 'liked_topics',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.alter_column('users', 'credits',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'tier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('user_memory', 'last_active',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('user_memory', 'interaction_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_memory', 'liked_topics',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.alter_column('user_memory', 'mood_history',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.alter_column('user_memory', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user_memory', 'structured_memory')
    op.drop_index(op.f('ix_training_jobs_id'), table_name='training_jobs')
    op.alter_column('training_jobs', 'job_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_training_data_user_id'), table_name='training_data')
    op.drop_index(op.f('ix_training_data_session_id'), table_name='training_data')
    op.drop_index(op.f('ix_training_data_id'), table_name='training_data')
    op.drop_index(op.f('ix_response_feedback_id'), table_name='response_feedback')
    op.alter_column('quotes', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('quotes', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('push_subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_prompt_performance_id'), table_name='prompt_performance')
    op.alter_column('prompt_performance', 'variant_idx',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payment_events', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('payment_events', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('payment_events', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('payment_events', 'amount',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.drop_index(op.f('ix_model_versions_id'), table_name='model_versions')
    op.alter_column('model_versions', 'model_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('model_versions', 'job_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_feed_items_timestamp'), table_name='feed_items')
    op.alter_column('feed_items', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('feed_items', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.alter_column('chat_history', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('chat_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('analytics', 'daily_users',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('analytics', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('analytics', 'chats_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('analytics', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index(op.f('ix_personas_user_id'), table_name='personas')
    op.drop_index(op.f('ix_personas_id'), table_name='personas')
    op.drop_table('personas')
    # ### end Alembic commands ###
