"""sync_analytics_and_push_subscription

Revision ID: 9dfdbb09c430
Revises: 1a48220d78bd
Create Date: 2026-03-22 16:28:01.057801

"""
from typing import Sequence, Union

from alembic import op # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dfdbb09c430'
down_revision: Union[str, Sequence[str], None] = '1a48220d78bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('daily_users', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.drop_column('analytics', 'likes_count')
    op.drop_column('analytics', 'daily_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('daily_users', sa.INTEGER(), nullable=True))
    op.add_column('analytics', sa.Column('likes_count', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
