"""sync_analytics_and_push_subscription

Revision ID: c05c8c32cadb
Revises: 9dfdbb09c430
Create Date: 2026-03-22 16:28:22.844221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c05c8c32cadb'
down_revision: Union[str, Sequence[str], None] = '9dfdbb09c430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.add_column('analytics', sa.Column('daily_users', sa.Integer(), nullable=True))
    op.drop_column('push_subscriptions', 'daily_users')
    op.drop_column('push_subscriptions', 'likes_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_subscriptions', sa.Column('likes_count', sa.INTEGER(), nullable=True))
    op.add_column('push_subscriptions', sa.Column('daily_users', sa.INTEGER(), nullable=True))
    op.drop_column('analytics', 'daily_users')
    op.drop_column('analytics', 'likes_count')
    # ### end Alembic commands ###
