"""add user_memory_log_table

Revision ID: dd5e6f6a7b8c
Revises: e08143c7b807
Create Date: 2026-03-24 13:50:00.000000

"""
from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa  # type: ignore


# revision identifiers, used by Alembic.
revision: str = 'dd5e6f6a7b8c'
down_revision: Union[str, Sequence[str], None] = 'e08143c7b807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_memory_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('response', sa.String(), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('embedding', sa.PickleType(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_memory_logs_id'), 'user_memory_logs', ['id'], unique=False)
    op.create_index(op.f('ix_user_memory_logs_user_id'), 'user_memory_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_memory_logs_user_id'), table_name='user_memory_logs')
    op.drop_index(op.f('ix_user_memory_logs_id'), table_name='user_memory_logs')
    op.drop_table('user_memory_logs')
    # ### end Alembic commands ###
