# infrastructure/neo4j/neo4j.conf

# 🛡️ Sovereign Hardening: Neo4j Backup
dbms.backup.enabled=true
dbms.backup.listen_address=0.0.0.0:6362

# Performance / RC1 Logic
dbms.memory.heap.initial_size=512m
dbms.memory.heap.max_size=1G
dbms.memory.pagecache.size=512m
dbms.security.auth_enabled=true

dbms.security.procedures.unrestricted=apoc.*

server.memory.pagecache.size=512M

server.default_listen_address=0.0.0.0
server.directories.logs=/logs
