import { getMyGallery } from './api.js';

document.addEventListener('DOMContentLoaded', async () => {
    const galleryGrid = document.getElementById('gallery-grid');
    const token = localStorage.getItem('levi_token');

    if (!token) {
        window.location.href = 'auth.html';
        return;
    }

    try {
        const items = await getMyGallery(token);

        if (items && items.length > 0) {
            galleryGrid.innerHTML = ''; // Clear container
            
            items.forEach(item => {
                const card = createGalleryCard(item);
                galleryGrid.appendChild(card);
            });
        } else {
            // Keep the default empty state already in HTML
        }
    } catch (err) {
        console.error("Gallery fetch failed:", err);
        window.ui.showToast("Failed to load your masterpieces.", "error");
    }
});

function createGalleryCard(item) {
    const div = document.createElement('div');
    div.className = 'group relative glass rounded-2xl overflow-hidden border border-white/10 hover:border-gold/30 transition-all duration-500 animate-fade-up';
    
    const mediaHtml = item.video 
        ? `<video src="${item.video}" class="w-full h-full object-cover" loop muted playsinline onmouseover="this.play()" onmouseout="this.pause()"></video>`
        : `<img src="${item.image}" alt="Wisdom" class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110">`;

    div.innerHTML = `
        <div class="aspect-[9/16] relative overflow-hidden">
            ${mediaHtml}
            <div class="absolute inset-0 bg-gradient-to-t from-[#09090f] via-transparent to-transparent opacity-60"></div>
            
            <div class="absolute bottom-0 left-0 right-0 p-6 translate-y-4 group-hover:translate-y-0 transition-transform duration-500">
                <p class="text-white text-sm font-medium mb-2 line-clamp-3 italic">"${item.text}"</p>
                <p class="text-gold text-xs font-bold uppercase tracking-widest">— ${item.author}</p>
                
                <div class="flex items-center gap-4 mt-4 opacity-0 group-hover:opacity-100 transition-opacity duration-500 delay-100">
                    <button onclick="downloadItem('${item.video || item.image}', '${item.video ? 'mp4' : 'png'}')" class="p-2 rounded-full bg-white/10 hover:bg-gold/20 text-white hover:text-gold transition-all">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a2 2 0 002 2h12a2 2 0 002-2v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/></svg>
                    </button>
                    <button onclick="shareItem('${item.text}', '${item.author}')" class="p-2 rounded-full bg-white/10 hover:bg-gold/20 text-white hover:text-gold transition-all">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z"/></svg>
                    </button>
                </div>
            </div>
        </div>
    `;
    return div;
}

// Helper functions for the buttons (can be global for simplicity)
window.downloadItem = (url, ext) => {
    const a = document.createElement('a');
    a.href = url;
    a.download = `levi-wisdom-${Date.now()}.${ext}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
};

window.shareItem = (text, author) => {
    if (navigator.share) {
        navigator.share({
            title: 'LEVI AI — Wisdom Saved',
            text: `"${text}" — ${author}`,
            url: window.location.origin
        });
    } else {
        navigator.clipboard.writeText(`"${text}" — ${author}\n\nGenerated by LEVI AI`);
        window.ui.showToast("Quote text copied!");
    }
};
