FROM rasa/rasa:3.6.20-full

WORKDIR /app

COPY rasa/requirements.txt .
RUN pip install -r requirements.txt

COPY rasa/ .

# Default command for rasa-server
CMD ["run", "--enable-api", "--cors", "*", "-m", "models", "--port", "5005", "--debug"]
