FROM rasa/rasa:3.6.20-full

WORKDIR /app

# Create and use a virtual environment
ENV PATH="/opt/venv/bin:$PATH"
RUN python -m venv /opt/venv

COPY rasa/requirements.txt .
RUN pip install -r requirements.txt

COPY rasa/ .

# Train the rasa model during build
RUN rasa train

# Default command for rasa-server
CMD ["run", "--enable-api", "--cors", "*", "-m", "models", "--port", "5005", "--debug"]
