FROM rasa/rasa:3.6.20-full

WORKDIR /app

# Create and use a virtual environment
ENV PATH="/opt/venv/bin:$PATH"
RUN python -m venv /opt/venv

COPY rasa/requirements.txt .
RUN pip install -r requirements.txt

COPY rasa/ .

# Default command for rasa-actions
CMD ["run", "actions", "--port", "5055"]
